module WWMD::VSStubs; end
require 'wwmd/viewstate/vs_stubs/vs_stub_helpers'
require 'wwmd/viewstate/vs_stubs/vs_read_value'
require 'wwmd/viewstate/vs_stubs/vs_read_types'
require 'wwmd/viewstate/vs_stubs/vs_value'
require 'wwmd/viewstate/vs_stubs/vs_array'
require 'wwmd/viewstate/vs_stubs/vs_binary_serialized'
require 'wwmd/viewstate/vs_stubs/vs_int_enum'
require 'wwmd/viewstate/vs_stubs/vs_hashtable'
require 'wwmd/viewstate/vs_stubs/vs_hybrid_dict'
require 'wwmd/viewstate/vs_stubs/vs_list'
require 'wwmd/viewstate/vs_stubs/vs_pair'
require 'wwmd/viewstate/vs_stubs/vs_sparse_array'
require 'wwmd/viewstate/vs_stubs/vs_string'
require 'wwmd/viewstate/vs_stubs/vs_string_array'
require 'wwmd/viewstate/vs_stubs/vs_string_formatted'
require 'wwmd/viewstate/vs_stubs/vs_triplet'
require 'wwmd/viewstate/vs_stubs/vs_type'
require 'wwmd/viewstate/vs_stubs/vs_unit'
require 'wwmd/viewstate/vs_stubs/vs_indexed_string'
require 'wwmd/viewstate/vs_stubs/vs_indexed_string_ref'

